### ISSUE TITLE
Scatter plot and Slider do not make sense

### ISSUE THREAD

**Issue by dansotoz** [Kranf99/kibella#77]
when I use a slider to apply a filter on a scatter plot, the values do not make sense 
Those two plots should be identical, the first one has no filter used. 
here is the JSON code of the slider
{
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "Promedio Delta": {
                  "gte": -0.3,
                  "lte": 0.1
                }
              }
            },
            {
              "query": {
                "query_string": {
                  "analyze_wildcard": true,
                  "query": "*"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "size": 0,
  "aggs": {}
}
![newplot(1)](https://user-images.githubusercontent.com/13632722/79035793-52e8a080-7b87-11ea-8907-f726f2cb8b19.png)
![newplot(2)](https://user-images.githubusercontent.com/13632722/79035778-38aec280-7b87-11ea-92ff-44edcf337390.png)

**Comment by mastropi** [comment]
Do you think this problem comes from the backend side or from the frontend side?

On my side (the backend), I can say that I have at least one passing unit test where the filter is based on a *variable range*. The filter seems to be working properly as the number of records coincide with those obtained by applying the same filter on the input table (CensusIncome).

I am attaching the query and response files for such unit test.

Note that the range filter is applied on a variable ("capital gains") that is also part of the Y-axis aggregations (as in your case).

[Bug02-Census-FilterOnFieldWithSpaces-MyResponse.txt](https://github.com/Kranf99/kibella/files/4464757/Bug02-Census-FilterOnFieldWithSpaces-MyResponse.txt)
[Bug02-Census-FilterOnFieldWithSpaces-Query-Beautified.txt](https://github.com/Kranf99/kibella/files/4464758/Bug02-Census-FilterOnFieldWithSpaces-Query-Beautified.txt)

If you think the problem comes from the backend side, do you think you could share the input data with me so I can investigate?

**Comment by Kranf99** [comment]
This seems to fixed with the latest release.
@dansotoz : could you confirm?

**Comment by mastropi** [comment]
I talked to Daniel on Tuesday and it seems this is still a problem.

He said he was using the latest version Kibella-v3.4 although we were not able to check that as the home page of Kibella does not work --see [issue #92](https://github.com/Kranf99/kibella/issues/92)

On the other hand, he sent me the JSON request string of the query related to the problem, which I tested on my side with another table and got no issues. I.e. the number of records 

@dansotoz: attached are **the query I ran and the response I received** on a table with 16,531 records, when a slider filter is applied to limit one of the plotted variables to the range [-9, 0].
In terms of the query you shared with me, the equivalences with my query are as follows:
your grouping variable `account_number` -> my `q20_CapDevDeuda`
your slider variable `gross_margin` -> my `ROE`
your other scatter plot variable `charges_SEK_byCount` -> my `importeAjustadovsVentas`

Note that the records returned in the response are the same I get when I run the equivalent SQL query on the SQLite Explorer by Timi:
![image](https://user-images.githubusercontent.com/12116544/83744696-cfb26b00-a65c-11ea-9f97-4947d803b702.png)



I also checked using the Slider and Scatter plot in a Kibella dashboard and things seem to be working fine.
Example:
![image](https://user-images.githubusercontent.com/12116544/83743534-228b2300-a65b-11ea-8ab7-b75b20a37bdc.png)

![image](https://user-images.githubusercontent.com/12116544/83745024-3f285a80-a65d-11ea-9fe0-b66f45d37020.png)


The only difference in terms of software used is that I am using the latest version of the JSON-SQL bridge, which I pushed last Monday to the respective repository. However, I haven't touched the aggregations related to this problem for quite a few months/year already...

The next steps I would suggest are:
1) Check that you are running the latest version of Kibella ([v3.4](https://github.com/Kranf99/kibella/releases/tag/v3.4), released on 28-May-2020)
2) If yes, share your data with me and I will try to reproduce the problem on my side.
